create table
  public.locker_lockers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    room character varying not null,
    locker_number integer not null,
    constraint locker_lockers_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.locker_ownerships (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    locker_id bigint not null,
    username character varying not null,
    start_date date not null,
    end_date date not null,
    constraint locker_ownerships_pkey primary key (id),
    constraint locker_ownerships_locker_id_fkey foreign key (locker_id) references locker_lockers (id)
  ) tablespace pg_default;

